<?php

/**
 * @file
 * A test module for views_advanced_cache.
 */

use Drupal\Core\Cache\Cache;
use Drupal\node\NodeInterface;

/**
 * Invalidate a custom node list cache tag on node save.
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node being saved.
 */
function views_advanced_cache_test_node_presave(NodeInterface $node) {
  $tags = ['vact:node_list:' . $node->getType()];
  Cache::invalidateTags($tags);
}
