<?php

	function base_structure_theme($existing, $type, $theme, $path) {
	  return [
		'logo_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/logo',
		],
		'socials_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/socials',
		],
		'banner_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/banner',
		],
		'products_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/products',
		],
		'services_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/services',
		],
		'news_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/news',
		],
		'testimonials_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/testimonials',
		],
		'methodology_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/methodology',
		],
		'partners_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/partners',
		],
		'values_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/values',
		],
		'clients_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/clients',
		],
		'links_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/links',
		],
		'contacts_block' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/contacts',
		],
		'map_block'=> [
			'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/map'
		],
		'subscribe_block'=> [
			'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'blocks/subscribe'
		],
		'about_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/about',
		],
		'products_services_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/products_services',
		],
		'products_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/products',
		],
		'services_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/services',
		],
		'news_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/news',
		],
		'faq_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/faq',
		],
		'contact_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/contact',
		],
		'page_403_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/page_403',
		],
		'page_404_view' => [ 
		  'variables' => [
				'titulo' =>'Titulo por defecto',
				'descripcion' => 'Descripción por defecto',
				'path' => $path,
				'data' => NULL,
				'attached' => NULL
			],
		  'template' => 'views/page_404',
		],
	  ];
	  
	}

	function base_structure_mail($key, &$message, $params) {

		switch ($key) {
			case 'feedback_form':
				$message['subject'] = $params['subject'];
				$message['body'][] = "Has recibido un nuevo mensaje desde el formulario de contacto:";
				$message['body'][] = "Nombre: " . $params['name'];
				$message['body'][] = "Correo: " . $params['email'];
				$message['body'][] = "Demo: " . $params['demo'];
				$message['body'][] = "Mensaje: " . $params['message'];
			break;
			case 'subscribe_form':
				$message['subject'] = "Subscripción a MagnusTI";
				$message['body'][] = "!Gracias por subscribirse!";
			break;
		}
	}


